# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Sigrid test"
client_id = "4510ff214b567be3bd8d269a68842f73"
handle = "sigrid-test"
application_url = "https://localhost:3000"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [ "https://localhost:3000/auth/callback" ]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-sigrid.myshopify.com"
